server: mystro.domain.com
token: usertoken

#local dev environment
#server: localhost:3000
#token: usertoken

# the account to use if one is not specified
default_account: default

# uncomment this and specify the accounts you want to support
# all others will be filtered from use.
#:accounts:
#  - default
#  - production

ssh:
  # user to connect as, when ssh'ing to server
  # AWS defaults to the user "ubuntu"
  user: ubuntu

logging:
  - ["debug", "log/mystro.log"]

workers: true

# if you're using the same provider for all of your cloud resources
# set them here
#connect:
#  fog:
#    provider: AWS
#    aws_access_key_id: access key
#    aws_secret_access_key: secret key
# otherwise, you will need to specify them below in each of the
# different services

compute:
  # defaults for all computes
  fog:
    region: us-east-1
#    # cloud provider configuration for computes
#    provider: AWS
#    aws_access_key_id: access key
#    aws_secret_access_key: secret key

  flavor: m1.large
  region: us-east-1
  groups:
    - default
  keypair: rgi-keypair-20120125
  image: ami-0145d268 # make sure this is an image in the region specified to fog.
  # userdata package to use
  userdata: default

balancer:
  something: true

dns:
  fog:
#    provider: AWS
#    aws_access_key_id: access key
#    aws_secret_access_key: secret key
#
#    provider: DNSMadeEasy
#    dnsmadeeasy_api_key: api key
#    dnsmadeeasy_secret_key: secret key
#
#    provider: Zerigo
#    zerigo_email: email
#    zerigo_token: token
  zone: subdomain.com

# plugins
plugins:
#  chef:
#    knife: config/chef/knife.rb

  #puppet:
    #TODO: Figure out the same thing for puppet

#  scout:
#    account: accountname
#    email:   your@email.com
#    secret:  password
